apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: Service-lb-demo

spec:
  type: LoadBalancer
  selector:
   purpose: Service-lb-demo
   project: roboshop
   environment: dev
  ports: 
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 # container port